/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.dry.entendaobjetosoo;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class frmClasseVisual extends javax.swing.JFrame {
    //Instância a classe veículo
    Veiculo veiculo1 = new Veiculo();
    /**
     * Creates new form frmClasseVisual
     */
    public frmClasseVisual() {
        initComponents();
        inserirIcone();
        setSize(410, 310);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAnoVeiculo = new javax.swing.JTextField();
        txtNomeVeiculo = new javax.swing.JTextField();
        btnAtributos = new javax.swing.JButton();
        btnAcelerar = new javax.swing.JButton();
        btnFrear = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ClasseVisual");
        setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        getContentPane().setLayout(null);

        jLabel2.setText("Ano do veiculo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 16);

        jLabel3.setText("Nome do Veiculo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 10, 110, 16);
        getContentPane().add(txtAnoVeiculo);
        txtAnoVeiculo.setBounds(10, 30, 80, 22);
        getContentPane().add(txtNomeVeiculo);
        txtNomeVeiculo.setBounds(140, 30, 100, 22);

        btnAtributos.setText("Atributos");
        btnAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtributosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtributos);
        btnAtributos.setBounds(10, 70, 90, 23);

        btnAcelerar.setText("Acelerar");
        btnAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcelerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcelerar);
        btnAcelerar.setBounds(110, 70, 73, 23);

        btnFrear.setText("Frear");
        btnFrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnFrear);
        btnFrear.setBounds(190, 70, 72, 23);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(270, 70, 72, 23);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(350, 70, 72, 23);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/dry/entendaobjetosoo/fundoCarro.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 400, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtributosActionPerformed
        // TODO add your handling code here:
        try
        {
            veiculo1.veiAno = (Integer.parseInt(txtAnoVeiculo.getText()));
            veiculo1.veiNome = txtNomeVeiculo.getText();
            if (veiculo1.veiNome.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Verifique se você deixou a caixa de texto nome do veiculo vazia!!!", "Erro na Entrada de Dados", JOptionPane.INFORMATION_MESSAGE);
                txtNomeVeiculo.requestFocus();
            } else {
                veiculo1.exibirAtributos();
            }
        }
        catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Verifique se você digitou algum caracter diferente de número\n ou deixou alguma caixa de texto ano veículo vazia!!", "Erro na Entrada de Dados", JOptionPane.INFORMATION_MESSAGE);
            txtAnoVeiculo.requestFocus();
        }
    }//GEN-LAST:event_btnAtributosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtAnoVeiculo.setText("0");
        txtNomeVeiculo.setText("0");
        txtAnoVeiculo.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcelerarActionPerformed
        // TODO add your handling code here:
        veiculo1.veiculoAcelerar();
    }//GEN-LAST:event_btnAcelerarActionPerformed

    private void btnFrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrearActionPerformed
        // TODO add your handling code here:
        veiculo1.veiculoFrear();
    }//GEN-LAST:event_btnFrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClasseVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClasseVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClasseVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClasseVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClasseVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcelerar;
    private javax.swing.JButton btnAtributos;
    private javax.swing.JButton btnFrear;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JTextField txtAnoVeiculo;
    private javax.swing.JTextField txtNomeVeiculo;
    // End of variables declaration//GEN-END:variables

    private void inserirIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png")));
    }
}
