/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.udf.usarobjetosoo;

import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class frmUsarTelevisor extends javax.swing.JFrame {
    //Instância a classe Televisor
    Televisor tv = new Televisor(); 
    /**
     * Creates new form frmUsarTelevisor
     */
    public frmUsarTelevisor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCanalTV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtVolumeTV = new javax.swing.JTextField();
        btnExibirDados = new javax.swing.JButton();
        btnTrocarCanal = new javax.swing.JButton();
        btnAumentarVolume = new javax.swing.JButton();
        btnDiminuirVolume = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Usando a Classe Televisor");
        setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usando a Classe Televisor"));

        jLabel1.setText("Digite um Canal:");

        jLabel2.setText("Volume da TV:");

        btnExibirDados.setText("Exibir Dados");
        btnExibirDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirDadosActionPerformed(evt);
            }
        });

        btnTrocarCanal.setText("Trocar Canal");
        btnTrocarCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocarCanalActionPerformed(evt);
            }
        });

        btnAumentarVolume.setText("Volume++");
        btnAumentarVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarVolumeActionPerformed(evt);
            }
        });

        btnDiminuirVolume.setText("Volume--");
        btnDiminuirVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiminuirVolumeActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(txtCanalTV)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVolumeTV))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExibirDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrocarCanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAumentarVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDiminuirVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCanalTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExibirDados)
                            .addComponent(btnDiminuirVolume))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTrocarCanal)
                        .addComponent(btnLimpar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVolumeTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAumentarVolume)
                    .addComponent(btnSair))
                .addGap(0, 175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void btnExibirDadosActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        try {
            tv.tvCanal = (Integer.parseInt(txtCanalTV.getText()));
            tv.tvVolume = (Integer.parseInt(txtVolumeTV.getText()));
            if ("".equals(txtCanalTV.getText()) || ("".equals(txtVolumeTV.getText()))) {
                JOptionPane.showMessageDialog(null, "Verifique se vc deixou alguma caixa de texto vazia!!", "Erro na entrada de dados", JOptionPane.INFORMATION_MESSAGE);
                txtCanalTV.requestFocus();
            } else {
                tv.exibirDados();
            }
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Verifique se vc deixou algum item vazio!!", "Erro na entrada de dados", JOptionPane.INFORMATION_MESSAGE);
            txtCanalTV.requestFocus();
        }
    }                                              

    private void btnTrocarCanalActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        try {
            tv.tvCanal = (Integer.parseInt(txtCanalTV.getText()));
            if ("".equals(txtCanalTV.getText())) {
                JOptionPane.showMessageDialog(null, "Verifique se vc deixou alguma caixa de texto vazia!!", "Erro na entrada de dados", JOptionPane.INFORMATION_MESSAGE);
                txtCanalTV.requestFocus();
            } else {
                tv.trocarCanal();
            }
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Verifique se vc deixou algum item vazio!!", "Erro na entrada de dados", JOptionPane.INFORMATION_MESSAGE);
            txtCanalTV.requestFocus();
        }    
    }                                              

    private void btnAumentarVolumeActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        try {
            tv.tvVolume = (Integer.parseInt(txtVolumeTV.getText()));
            if ("".equals(txtVolumeTV.getText())) {
                JOptionPane.showMessageDialog(null, "Verifique se vc deixou a caixa de texto volume da TV vazia", "Erro na entrada de dados", JOptionPane.INFORMATION_MESSAGE);
                txtVolumeTV.requestFocus();
            } else {
                tv.aumentarVolume();
            }
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Verifique se vc deixou a caixa de texto volume da TV vazia!!", "Erro na entrada de dados", JOptionPane.INFORMATION_MESSAGE);
            txtVolumeTV.requestFocus();
        }
    }                                                 

    private void btnDiminuirVolumeActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        try {
            tv.tvVolume = (Integer.parseInt(txtVolumeTV.getText()));
            if ("".equals(txtVolumeTV.getText())) {
                JOptionPane.showMessageDialog(null, "Verifique se vc deixou a caixa de texto volume da TV vazia!!", "Erro na entrada de dados", JOptionPane.INFORMATION_MESSAGE);
                txtVolumeTV.requestFocus();
            } else {
                tv.diminuirVolume();
            }
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Verifique se vc deixou a caixa de texto volume da TV vazia!!", "Erro na entrada de dados", JOptionPane.INFORMATION_MESSAGE);
            txtVolumeTV.requestFocus();
        }
    }                                                 

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        txtCanalTV.setText("");
        txtVolumeTV.setText("");
        txtCanalTV.requestFocus();
    }                                         

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Deseja sair do programa?", "***Saindo do programa***", JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        } else {
            txtCanalTV.requestFocus();
        }
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsarTelevisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsarTelevisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsarTelevisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsarTelevisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsarTelevisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAumentarVolume;
    private javax.swing.JButton btnDiminuirVolume;
    private javax.swing.JButton btnExibirDados;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTrocarCanal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCanalTV;
    private javax.swing.JTextField txtVolumeTV;
    // End of variables declaration                   
}
