select * from gafanhotos;
select * from cursos;
select * from cursos order by nome asc;
select ano, nome, carga from cursos order by ano, nome;
select nome, carga from cursos where ano = '2016' order by nome;
select nome, descricao, ano from cursos where ano = '2016' order by ano, nome;
select nome, ano from cursos where ano between 2014 and 2016 order by ano desc, nome; 
select nome, descricao, ano from cursos where ano in ('2014', '2016', '2020') order by ano;
select nome, carga, totaulas from cursos where carga > 35 or totaulas < 30 order by nome;
select * from cursos where nome like '%a%' order by  idcurso;
select * from cursos where nome not like '%a%' order by idcurso;
select * from cursos where nome like 'ph%p_';
select * from gafanhotos where nome like '%silva';
select distinct nacionalidade from gafanhotos order by nacionalidade;
select distinct carga from cursos order by carga;
select count(*) from cursos;
select count(*) from cursos where carga > 40;
select max(carga) from cursos;
select * from cursos where ano = '2016';
select max(totaulas) from cursos where ano = '2016';
select min(totaulas) from cursos where ano = '2016';
select nome, min(totaulas) from cursos where ano = '2016';
select sum(totaulas) from cursos where ano = '2016';
select * from cursos;
select avg(totaulas) from cursos where ano = '2016';
select carga from cursos group by carga;
select totaulas, count(*) from cursos group by totaulas order by totaulas;
select carga, count(nome) from cursos where totaulas = 30 group by carga;
select * from cursos where totaulas = 30;
select ano, count(*) from cursos group by ano having count(ano) >= 5 order by count(*) desc;
select carga, count(*) from cursos where ano > 2015 group by carga having carga > (select avg(carga) from cursos);

select * from gafanhotos;
select nome, nacionalidade from gafanhotos where sexo = 'f';
select * from gafanhotos where nascimento between '2000-01-01' and '2015-12-31';
select nome, profissao from gafanhotos where sexo = 'M' and profissao = 'programador';
select * from gafanhotos where sexo = 'F' and nacionalidade = 'Brasil' and nome like 'J%';
select nome, nacionalidade from gafanhotos where sexo = 'M' and nome like '%Silva%' and nacionalidade <> 'Brasil' and peso < '100'; 
select max(altura) from gafanhotos where sexo = 'M' and nacionalidade = 'Brasil';
select avg(peso) from gafanhotos;
select min(peso), nome from gafanhotos where sexo = 'F' and nacionalidade <> 'Brasil' between '1990-01-01' and '2000-12-31';
select count(altura) from gafanhotos where sexo = 'F' and altura >= '1.90';
select profissao, count(*) from gafanhotos group by profissao order by count(*);
select sexo, count(sexo) from gafanhotos where nascimento > '2005-01-01' group by sexo order by sexo;
select nacionalidade, count(*) from gafanhotos where nacionalidade <> 'Brasil' group by nacionalidade having count(nacionalidade) > 3 order by count(*);
select nacionalidade, count(nacionalidade) from gafanhotos group by nacionalidade;
select altura, peso, count(*) from gafanhotos where peso > '100' group by altura having altura > (select avg(altura) from gafanhotos) order by altura;
select avg(altura) from gafanhotos;


update cursos set nome = 'PáOO' where idcurso = '9';
